apiVersion: app/v1
kind: Deployment
metadata:
  name: app1-rs
  labels:
    app: app1
    type: front-end
spec:
  template: 
    metadata:
      name: app1-pod
      labels:
        app: app1
        type: front-end
    spec:
      containers:
      - image: nginx
        name: nginx-container
  replicas: 6
  selector:
    matchLabels:
      type: front-end
      app: app1